name: Firebase Secret Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Firebase credentials
        run: |
          mkdir -p storage/firebase
          cat <<EOF > storage/firebase/service-account.json
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          EOF
